from sqlalchemy import String
from sqlalchemy import JSON
from sqlalchemy import DateTime

from sqlalchemy.orm import Mapped
from sqlalchemy.orm import mapped_column

from datetime import datetime

from app.core.database import Base


# Event model for storing user activity and analytics events
class Event(Base):

    __tablename__ = "events"

    # Primary key for each event
    id: Mapped[int] = mapped_column(
        primary_key=True
    )

    # Type of event generated by user activity
    event_type: Mapped[str] = mapped_column(
        String(100)
    )

    # Email of the user who triggered the event
    user_email: Mapped[str] = mapped_column(
        String(255)
    )

    # Flexible JSON metadata for event details
    event_metadata: Mapped[dict] = mapped_column(
        JSON
    )

    # Timestamp when the event was created
    created_at: Mapped[datetime] = mapped_column(
        DateTime,
        default=datetime.utcnow
    )